# Generated by Django 3.1.6 on 2021-10-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0002_auto_20210928_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='relationship',
            field=models.CharField(choices=[('We work together in the same team or on the same project', 'We work together in the same team or on the same project'), ('Blaise was under my responsability', 'Blaise was under my responsability'), ('We work together inderectly', 'We work together inderectly'), ('I was his customer', 'I was his customer'), ('I heard about his skills', 'I heard about his skills')], max_length=200),
        ),
    ]
