# Generated by Django 3.2.9 on 2021-11-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_message_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
