# Generated by Django 3.2.9 on 2021-11-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendation', '0003_auto_20211012_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
